### ISSUE TITLE
rename master to main

### ISSUE THREAD

**Issue by gernotstarke** [gernotstarke/esabuch.de-site#44]
a bit of git magic will do this trick...

**Comment by Per-Starke** [comment]
@gernotstarke My privileges are not sufficient for that. I need either your login or you need to give me full admin access for this repo, otherwise I can't fully close this issue

**Comment by gernotstarke** [comment]
hhm - not possible with my current account type (personal) - that's only possible in organization-accounts (like arc42)...

**Comment by Per-Starke** [comment]
@gernotstarke Hmm okay, well then you have to do some of the steps. I already prepared everything so far.

I have created the main-branch, it is up to date with the master branch. 

Now **YOU** need to:
- Choose "main" as the default branch instead of master
- Delete "master"
You should be able to do that from the GitHub Website.

For your local repo, if you want to use it, you need to perform some steps as well, so you also have the renamed version locally:
```
# Switch to the "master" branch:
$ git checkout master

# Rename it to "main":
$ git branch -m master main

# Get the latest commits (and branches!) from the remote:
$ git fetch

# Remove the existing tracking connection with "origin/master":
$ git branch --unset-upstream

# Create a new tracking connection with the new "origin/main" branch:
$ git branch -u origin/main
```
