### ISSUE TITLE
propose new site-layout/navigation

### ISSUE THREAD

**Issue by gernotstarke** [gernotstarke/esabuch.de-site#48]
maybe use this as another example for your homepage canvas, @Per-Starke 

I'm open for suggestions. 

Needed:

* Literaturverweise (aus dem Buch, aber mit echten Links)
* Errata
* Hinweise auf Training und Consulting (ggfs. auch Termine)
* ein paar Downloads von "Goodies" aus dem Buch
* über mich ("Autor"), Kurzprofile

* Vorbereitung auf iSAQB Prüfung

**Comment by Per-Starke** [comment]
Yeah using this as a canvas example would be amazing!

Quick questions before I propose a new structure:
How much content do you want on the "downloads", "isaqb-vorbereitung" and "hinweise auf Training" pages? Because if its a lot of content, I would suggest separate pages for all of those, if it's not a lot, we could do a "More" section and put these 3 on a nicely styled single page. 

I'll propose a slightly nicer overall layout first, will show you a suggestion, without changing the structure, and then do the structure in the second step.
